version: "3"
services:
  examo-topic-classification:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ".:/app"
    image: examo_topic_classification:latest
#    command: "uvicorn main:app --host 0.0.0.0 --port 8880"
    env_file:
      - .env

